// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI agent that refines an email reply draft.
 *
 * - improveReplyDraft - A function that refines an email reply draft.
 * - ImproveReplyDraftInput - The input type for the improveReplyDraft function.
 * - ImproveReplyDraftOutput - The return type for the improveReplyDraft function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveReplyDraftInputSchema = z.object({
  draft: z
    .string()
    .describe('The email reply draft to be refined.'),
});
export type ImproveReplyDraftInput = z.infer<typeof ImproveReplyDraftInputSchema>;

const ImproveReplyDraftOutputSchema = z.object({
  refinedDraft: z.string().describe('The refined email reply draft.'),
});
export type ImproveReplyDraftOutput = z.infer<typeof ImproveReplyDraftOutputSchema>;

export async function improveReplyDraft(input: ImproveReplyDraftInput): Promise<ImproveReplyDraftOutput> {
  return improveReplyDraftFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveReplyDraftPrompt',
  input: {schema: ImproveReplyDraftInputSchema},
  output: {schema: ImproveReplyDraftOutputSchema},
  prompt: `You are an AI assistant specialized in refining email drafts.
      Your task is to improve the provided draft in terms of tone, grammar, and overall professionalism.
      Make sure the refined draft maintains the original intent while making it more polished and effective.

      Draft: {{{draft}}}

      Refined Draft:`,
});

const improveReplyDraftFlow = ai.defineFlow(
  {
    name: 'improveReplyDraftFlow',
    inputSchema: ImproveReplyDraftInputSchema,
    outputSchema: ImproveReplyDraftOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
